/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/t2FzPqLEgx2
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from "react"
import axios from "axios"
import { Sparkles, X, Plus, SendHorizontal } from "lucide-react"

const BACKEND_UPLOAD_URL = "http://localhost:3000";

export function Landing() {
  const [repoUrl, setRepoUrl] = useState("");
  const [uploadId, setUploadId] = useState("");
  const [uploading, setUploading] = useState(false);
  const [deployed, setDeployed] = useState(false);
  const [askPrompt, setAskPrompt] = useState("");
  const [askLoading, setAskLoading] = useState(false);
  const [askAnswer, setAskAnswer] = useState("");
  const [askError, setAskError] = useState("");
  const [showAskSidebar, setShowAskSidebar] = useState(false);

  return (
    <main className="relative flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-amber-50 via-orange-50 to-stone-100 p-4">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(180,83,9,0.15),transparent_40%),radial-gradient(circle_at_80%_10%,rgba(120,53,15,0.12),transparent_35%)]" />
      <Card className="relative w-full max-w-md border-amber-100/70 bg-white/90 shadow-xl backdrop-blur">
        <CardHeader>
          <CardTitle className="text-xl">Deploy your GitHub Repository</CardTitle>
          <CardDescription>Enter the URL of your GitHub repository to deploy it</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="github-url">GitHub Repository URL</Label>
              <Input 
                onChange={(e) => {
                  setRepoUrl(e.target.value);
                }} 
                placeholder="https://github.com/username/repo" 
              />
            </div>
            <Button onClick={async () => {
              setUploading(true);
              const res = await axios.post(`${BACKEND_UPLOAD_URL}/deploy`, {
                repoUrl: repoUrl
              });
              setUploadId(res.data.id);
              setUploading(false);
              const interval = setInterval(async () => {
                const response = await axios.get(`${BACKEND_UPLOAD_URL}/status?id=${res.data.id}`);

                if (response.data.status === "deployed") {
                  clearInterval(interval);
                  setDeployed(true);
                }
              }, 3000)
            }} disabled={uploadId !== "" || uploading} className="w-full" type="submit">
              {uploadId ? `Deploying (${uploadId})` : uploading ? "Uploading..." : "Upload"}
            </Button>

          </div>
        </CardContent>
      </Card>
      {deployed && <Card className="relative mt-8 w-full max-w-md border-amber-100/70 bg-white/90 shadow-xl backdrop-blur">
        <CardHeader>
          <CardTitle className="text-xl">Deployment Status</CardTitle>
          <CardDescription>Your website is successfully deployed!</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            <Label htmlFor="deployed-url">Deployed URL</Label>
            <Input id="deployed-url" readOnly type="url" value={`http://${uploadId}.dev.100xdevs.com:3001/index.html`} />
          </div>
          <br />
          <Button className="w-full" variant="outline">
            <a href={`http://${uploadId}.10kdevs.com/index.html`} target="_blank">
              Visit Website
            </a>
          </Button>
        </CardContent>
      </Card>}

      <Button
        type="button"
        onClick={() => setShowAskSidebar((prev) => !prev)}
        className="fixed left-6 top-6 z-50 h-12 rounded-full border border-amber-800/20 bg-gradient-to-br from-amber-600 via-orange-700 to-amber-900 px-4 shadow-lg shadow-amber-900/30 transition hover:scale-105 hover:brightness-110"
        aria-label="Open AI assistant"
      >
        <div className="flex items-center gap-2 rounded-full bg-black/15 px-1 py-1 backdrop-blur">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-white/25">
            <Sparkles className="h-4 w-4 text-white" />
          </div>
          <span className="pr-2 text-sm font-semibold text-white">Ask AI</span>
        </div>
      </Button>

      <aside
        className={`fixed right-0 top-0 z-40 h-full w-full max-w-md border-l border-amber-900/40 bg-[#120d09] p-4 text-stone-100 shadow-2xl transition-transform duration-300 ${showAskSidebar ? "translate-x-0" : "translate-x-full"}`}
      >
        <div className="mb-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-amber-500 via-orange-600 to-amber-800 text-white shadow">
              <Sparkles className="h-5 w-5" />
            </div>
            <div>
              <p className="text-base font-semibold text-slate-100">Ask AI</p>
              <p className="text-xs text-amber-200/70">Your smart assistant</p>
            </div>
          </div>
          <button
            type="button"
            onClick={() => setShowAskSidebar(false)}
            className="rounded-md p-2 text-stone-400 transition hover:bg-amber-950/50 hover:text-stone-100"
            aria-label="Close ask sidebar"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="flex h-[calc(100%-64px)] flex-col">
          <div className="flex-1 overflow-auto rounded-2xl border border-amber-900/40 bg-[#1a130e] p-4">
            <div className="mb-8 pt-2">
              <p className="text-4xl font-semibold text-amber-200">Hello, Anand</p>
              <p className="mt-2 text-4xl font-semibold leading-tight text-stone-300">How can I help you today?</p>
            </div>

            <div className="space-y-3">
              {[
                "List core features offered",
                "Break down a new concept for me",
                "Help me make a decision",
              ].map((prompt) => (
                <button
                  key={prompt}
                  type="button"
                  onClick={() => setAskPrompt(prompt)}
                  className="w-full rounded-full border border-amber-900/30 bg-[#241a14] px-4 py-3 text-left text-sm text-amber-100/90 transition hover:bg-[#31231b]"
                >
                  {prompt}
                </button>
              ))}
            </div>

            {askError && <p className="mt-4 text-sm text-rose-300">{askError}</p>}
            {askAnswer && (
              <div className="mt-4 max-h-[32vh] overflow-auto rounded-xl border border-amber-900/40 bg-[#241a14] p-3 text-sm text-stone-200">
                {askAnswer}
              </div>
            )}
          </div>

          <div className="mt-3 rounded-2xl border border-amber-900/40 bg-[#1a130e] p-2">
            <Label htmlFor="ask-ai-prompt" className="sr-only">Search / Prompt</Label>
            <div className="flex items-center gap-2">
              <button
                type="button"
                className="rounded-md p-2 text-stone-400 transition hover:bg-amber-950/40 hover:text-stone-200"
                aria-label="Add"
              >
                <Plus className="h-4 w-4" />
              </button>
              <Input
                id="ask-ai-prompt"
                value={askPrompt}
                onChange={(e) => setAskPrompt(e.target.value)}
                placeholder="Type your question..."
                className="border-0 bg-transparent text-stone-100 placeholder:text-stone-500 focus-visible:ring-0"
              />
              <Button
                onClick={async () => {
                  setAskError("");
                  setAskAnswer("");
                  if (!askPrompt.trim()) return;
                  setAskLoading(true);
                  try {
                    const res = await axios.post(`${BACKEND_UPLOAD_URL}/ask`, {
                      prompt: askPrompt
                    });
                    setAskAnswer(res.data.answer || "No response generated.");
                  } catch (error: unknown) {
                    if (axios.isAxiosError(error)) {
                      setAskError(error.response?.data?.error || "Failed to get AI response");
                    } else {
                      setAskError("Failed to get AI response");
                    }
                  } finally {
                    setAskLoading(false);
                  }
                }}
                disabled={askLoading || !askPrompt.trim()}
                className="h-9 w-9 rounded-lg bg-gradient-to-r from-amber-500 to-orange-700 p-0 text-white hover:brightness-110"
                type="button"
              >
                {askLoading ? <Sparkles className="h-4 w-4 animate-pulse" /> : <SendHorizontal className="h-4 w-4" />}
              </Button>
            </div>
          </div>
        </div>
      </aside>
    </main>
  )
}
